import { Injectable } from '@angular/core';

import { Report, ReportContent } from '../../core/models';

/**
 * Downloads a report as DOCX, and prints it as PDF.
 *
 * Both run in the browser — the API has no export endpoint. The DOCX is real
 * OOXML built with the `docx` library, not an HTML file with a .docx name.
 */
@Injectable({ providedIn: 'root' })
export class ReportExportService {
  /**
   * Build and download a .docx.
   *
   * The library is imported lazily so its weight only loads when someone
   * actually exports, keeping it out of the initial bundle.
   */
  async downloadDocx(report: Report, content: ReportContent): Promise<void> {
    const { Document, Packer, Paragraph, HeadingLevel, TextRun } = await import('docx');

    const children: InstanceType<typeof Paragraph>[] = [];

    children.push(
      new Paragraph({ text: content.title || report.title, heading: HeadingLevel.TITLE }),
      new Paragraph({
        children: [
          new TextRun({
            text: `${report.status} · version ${report.version} · ${formatDate(report.created_at)}`,
            italics: true,
          }),
        ],
      }),
      new Paragraph({ text: '' }),
    );

    const summary = content.summary ?? report.summary;
    if (summary) {
      children.push(new Paragraph({ text: 'Summary', heading: HeadingLevel.HEADING_1 }));
      for (const line of paragraphsOf(summary)) {
        children.push(new Paragraph({ text: line }));
      }
      children.push(new Paragraph({ text: '' }));
    }

    for (const section of content.sections ?? []) {
      children.push(new Paragraph({ text: section.heading ?? '', heading: HeadingLevel.HEADING_1 }));
      for (const line of paragraphsOf(section.body ?? '')) {
        children.push(new Paragraph({ text: line }));
      }
      children.push(new Paragraph({ text: '' }));
    }

    const citations = content.citations ?? [];
    if (citations.length) {
      children.push(new Paragraph({ text: 'Citations', heading: HeadingLevel.HEADING_1 }));
      citations.forEach((citation, index) => {
        const marker = citation.source ? ` ${citation.source}` : '';
        children.push(
          new Paragraph({ text: `${index + 1}. ${citation.claim ?? ''}${marker}` }),
        );
      });
      children.push(new Paragraph({ text: '' }));
    }

    // Provenance, so an exported file still says how it was produced.
    const provenance = content.generated_by as { provider?: string; model?: string } | undefined;
    if (provenance?.model) {
      children.push(
        new Paragraph({
          children: [
            new TextRun({
              text: `Generated by ${provenance.model}${provenance.provider ? ` (${provenance.provider})` : ''}.`,
              italics: true,
              size: 18,
            }),
          ],
        }),
      );
    }

    const document = new Document({ sections: [{ children }] });
    const blob = await Packer.toBlob(document);

    save(blob, `${slug(content.title || report.title)}.docx`);
  }

  /**
   * PDF via the browser's own print-to-PDF.
   *
   * A print stylesheet (see styles.scss) strips the shell, the chat panel and
   * every control, so what prints is the report itself.
   */
  printPdf(): void {
    window.print();
  }
}

function save(blob: Blob, filename: string): void {
  const url = URL.createObjectURL(blob);
  const anchor = document.createElement('a');
  anchor.href = url;
  anchor.download = filename;
  anchor.click();
  // Revoking immediately can cancel the download in some browsers.
  setTimeout(() => URL.revokeObjectURL(url), 1000);
}

/** Report bodies keep their own line breaks; Word needs one paragraph each. */
function paragraphsOf(text: string): string[] {
  return text.split(/\n+/).map((line) => line.trim()).filter(Boolean);
}

function slug(title: string): string {
  return (
    title
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, '-')
      .replace(/^-+|-+$/g, '')
      .slice(0, 60) || 'report'
  );
}

function formatDate(iso: string): string {
  return new Date(iso).toLocaleDateString();
}
